### 포인트 조회
GET localhost:8080/point/3

### 포인트 충전/이용 내역 조회
GET localhost:8080/point/3/histories

### 포인트 충전
PATCH localhost:8080/point/3/charge
Content-Type: application/json

10000

### 포인트 사용
PATCH localhost:8080/point/3/use
Content-Type: application/json

10000